### ISSUE TITLE
Issues running an application

### ISSUE THREAD

**Issue by jakelever** [openminted/Open-Call-Discussions#1]
Hi, I haven't been able to run any of the current applications on a corpus yet. I'm using the http://test.openminted.eu platform

Most recently I tried the options shown below and received the error message (There was a problem running the application. Try again in a while) after less than a minute.

Corpus: OpenMinTeD subset of OpenAIRE publications on term "Thalamus"
Application: Named Entity Recognizer for metabolites

Here's the process page
![openminted_error](https://user-images.githubusercontent.com/3662147/38294297-3e5e39fa-379f-11e8-99d5-d66f92725ee1.png)

And my operations page
![openminted_myoperations](https://user-images.githubusercontent.com/3662147/38294425-a6aed69a-379f-11e8-8d82-c7f17924dac9.png)

I noted this in a Google group thread (https://groups.google.com/forum/#!topic/openminted-user-forum/n8WQ8-KkS7g) and it appears some others are able to run applications. Is there an issue with my account?

Also is there a way to check the log to see why it failed?

**Comment by galanisd** [comment]
I had a look into test.openminted.eu. It seems that you run this app https://test.openminted.eu/landingPage/application/1b328c76-199c-4027-8dd0-f5f712e9b149.
which is an old test app which we were using for demonstrations. I do not think that 
it follows the latest specs of OpenMinTeD project (metadata + creation of docker image). So I assume this is why you are getting this error.   I am planning to delete it from test.openminted.eu. Probably someone used it to test registration. 

This app has been replaced I think with the following 
https://test.openminted.eu/landingPage/application/756502de-a422-4ba4-9c95-04a7d5e9e28c
which follows the OpenMinTeD specs and I have tested it several times in the last few days.

Dimitris

**Comment by jakelever** [comment]
I tried out the other component that you suggested (with the Thalamus corpus) and have left it running for over 12 hours but it doesn't seem to complete. Do you know what would be the expected runtime for this task? Also the "My Operations" page shows this process as still Running, but also a lot of previous attempts as also still "Running".

![openminted_error3](https://user-images.githubusercontent.com/3662147/38397921-0d9c48e6-38f5-11e8-8a72-3781e3df1006.png)

**Comment by galanisd** [comment]
I had the same issue with this combination ("thalamus" corpus + chebi web service ) on Wednesday (2 days ago). It was running for over 3-4 hours. I checked the logs etc. It seems that Chebi service gets stuck in a specific file of the corpus (which contains 3 PDFs). 

I reported it to Nhung I think she did some changes after that to Chebi service.

Also I just had a look into Galaxy and it seems that a corpus (I think "thalamus") has been successfully processed with Chebi in the last hour. I do not know if in the meantime something changed in the Chebi service.

**Comment by nguyennth** [comment]
Hi,

I did some changes to Chebi webservice on Wednesday. Today, I just tried the same operation as @jakelever did and successfully got the output here: https://test.openminted.eu/landingPage/corpus/d1bdf587-dd84-4f49-9ce3-fae9a5f7f04b

Here is my operation:
![image](https://user-images.githubusercontent.com/22884006/38421795-44f83c7c-39a0-11e8-817b-caff9174e32b.png)

**Comment by jakelever** [comment]
Thanks @nguyennth . I can confirm that it works for me.
