### ISSUE TITLE
Document language

### ISSUE THREAD

**Issue by reckart** [openminted/Open-Call-Discussions#11]
Does OMTD set the document language in the PdfReader or do you expect that the language is set on all components in the workflow individually?

**Comment by reckart** [comment]
@galanisd I guess if I am building a workflow which includes the omtdImporter and the PdfReader, then it is my responsibility to set the language parameter...

**Comment by reckart** [comment]
... which takes me back to #10 (not being able to change the configuration of components in a workflow after loading it again).

**Comment by galanisd** [comment]
> @galanisd I guess if I am building a workflow which includes the omtdImporter and the PdfReader, then it is my responsibility to set the language parameter...

Yes exactly.

> ... which takes me back to #10 (not being able to change the configuration of components in a workflow after loading it again).

I replied for this in https://github.com/openminted/Open-Call-Discussions/issues/10

**Comment by reckart** [comment]
Thanks :)
