### ISSUE TITLE
System error getting execution status (Server responded: undefined)

### ISSUE THREAD

**Issue by JKChang2015** [openminted/Open-Call-Discussions#15]
Hi,

I registered three chemical articles as a test corpus today (named chebi 3 articles), but it fail to process.  It says System error getting execution status (Server responded: undefined).

<img width="1318" alt="screen shot 2018-04-09 at 15 14 06" src="https://user-images.githubusercontent.com/16242098/38502938-ade748d0-3c08-11e8-895b-2bcd6dceadd5.png">

**Comment by galanisd** [comment]
Same corpus + same app. Clicked RUN...started processing. See screenshot...
![screenshot from 2018-04-09 20 10 36](https://user-images.githubusercontent.com/10739759/38511880-4151d79c-3c32-11e8-838f-0ff3916cf98f.png)

**Comment by galanisd** [comment]
However, from a quick look in the execution backend the data are never copied to our execution engine.
We have to check the corpus format. I have ran this service/app with several corpora and got results.

**Comment by galanisd** [comment]
Closing it since we have tested this app several times.
