### ISSUE TITLE
Expose Workflow Service Status Messages

### ISSUE THREAD

**Issue by greenwoodma** [openminted/Open-Call-Discussions#17]
At the moment it's difficult for a user of the platform to know why a workflow has failed or is stuck forever in the running state -- it's also difficult for us to debug such issues.

The workflow service adds useful information when errors occur to the status messages that are passed back to the registry (including when the status is set to failed). Could these messages be concatenated together and provided as a poor mans version of a log file. Should be easy to implement as the other alternative is some more central logging system which would be more time consuming to add to the platform at this late stage.

**Comment by greenwoodma** [comment]
another option would be to configure the docker images that run the components in such a way that we capture syslog and return that to the registry. @saxtouri is this feasible

**Comment by gkirtzou** [comment]
@greenwoodma from what I can see both the workflow service (https://github.com/openminted/omtd-workflow-service/blob/master/src/main/java/eu/openminted/workflow/service/WorkflowServiceImpl.java#L500) and the registry backend (https://github.com/openminted/omtd-registry/blob/develop/src/main/java/eu/openminted/registry/messages/OperationHandler.java#L254) do handle failed cases with error messages. Probably the UI needs to display this information.

**Comment by greenwoodma** [comment]
Sorry @gkirtzou poor choice of words on my part. Yes I meant we need the platform UI to expose the error messages to the user; for some reason I keep saying registry when I actually mean the UI.

@smartziou is this something you could look at adding?

**Comment by antleb** [comment]
Please use redmine for internal issue reporting. Lets keep this project for the public.

**Comment by greenwoodma** [comment]
@antleb normally I'd agree, but this came out of numerous publicly reported issues, and hence it would be useful to track the progress of fixing this publicly as well so that participants can see when more logging info etc. becomes available to them.

**Comment by greenwoodma** [comment]
Closing this as we've now added more error reporting into the workflow service and this seems to be showing up in the UI when workflows fail (more feedback from deeper into the execution would be nice but I think we have enough now to handle most cases).
