### ISSUE TITLE
Where is my component?

### ISSUE THREAD

**Issue by joancf** [openminted/Open-Call-Discussions#18]
I added two components (a week ago) to the test platform as indicated in your mails.
It seem to run, i got a final screen and this address
https://test.openminted.eu/landingPage/component/4d6b6339-9ec1-4042-80c7-469a76a59654
and 
https://test.openminted.eu/landingPage/component/3efc03d4-0091-404c-9fda-5ce11bb77a95

but today they are not there anymore and when entering with my user it indicates that I don't have any components in the system. :-( 

Have I done something wrong?
I hope I don't have to fill it again!

**Comment by greenwoodma** [comment]
I could be wrong but given these were submitted to the test platform (see the URL) then any upgrades to the platform that happen as bugs are fixed etc. may have resulted in the existing set of registered components being removed.

@antleb can you comment on what happens to test when it's updated?

**Comment by joancf** [comment]
But we received that mail some days ago!

> Dear all,
> Please note that to register your app you have to use test.openminted.eu instead of
> https://services.openminted.eu/
> Regards,
> -- 
> Montserrat Marimon.-
> montserrat.marimon@gmail.com
> Barcelona Supercomputing Center –
> Centro Nacional de Supercomputación,
> Life Sciences Department,
> Carrer de Jordi Girona, 29-31,
> Barcelona 08034,
> Spain
> tel. +34 93 4137569

**Comment by greenwoodma** [comment]
Afraid I don't know. I know test is the version that has the latest stable code but I'm not sure what if any guarantees are made for that version.

**Comment by galanisd** [comment]
I had a look into the logs, etc of the machine that hosts test.openminted.eu. It has not been updated for ~ 2 weeks. I assume that the issue you are reporting has to do with the content of metadata database & the index. Something was deleted from there.

**Comment by antleb** [comment]
In one of the initial questions for the open call, I replied that you can use test.openminted.eu for testing your components and their metadata but there are no guarantees on how long they will survive there. When everything is tested and ready, you'll have to register it to services.openminted.eu, which is stable and backed up regularly. In this particular case, I don't know yet what happened and we'll investigate.

However, please wait a bit before registering components or applications to services.openminted.eu until further notice. We are performing upgrades and maintenance to it and it would be better to wait for this process to finish. I'll let you know when to use it.

**Comment by reckart** [comment]
If your components are based on UIMA or GATE and Maven, I would recommend making use of the [OMTD-SHARE Maven plugin](http://localhost:4000/releases/omtd-share-annotations/). That should help you auto-generate the OMTD-SHARE XML files from data from your Maven POM and GATE/UIMA descriptors that you have anyway (or should add it you do not have it).

**Comment by reckart** [comment]
The OMTD-SHARE Maven plugin also automatically validates the generated descriptors - so it will tell you if anything is wrong/missing from the descriptor **before** you put it on the platform.

**Comment by joancf** [comment]
But my components are dockers

**Comment by jakelever** [comment]
Hey, I faced the same challenge. If you re-enter the component details in the menu, you can save the generated OMTD-SHARE XML file. It's on the My Components screen. Then if the platform gets wiped again, you can upload your Docker component using that file instead of having to fill out the form again. Hope that helps.

**Comment by joancf** [comment]
Thanks  @jakelever 
but I can't find the "save" method. 
I have the components screen but then ... there is no option to download it.

**Comment by ragerri** [comment]
On the right hand side of the screen there is a button to download the XML
descriptor. The last button under "Actions"

R
