### ISSUE TITLE
omtd descriptor and docker run command (clarification)

### ISSUE THREAD

**Issue by ragerri** [openminted/Open-Call-Discussions#23]
Hello,

I have added a component today which I hope follows the 1.0.0 specs. The way we run it locally is like this: 

docker run -v /home/user/corpus_in:/corpus_in -v /home/user/corpus_out:/corpus_out -i ragerri/en-ixa-pipes-omtd:0.0.1 /en-ixa-pipes.sh --input corpus_in --output corpus_out

It takes an input directory containing XMI files and outputs the result to an output directory in XMI format. 

In the attachment you can see the omtd spec of the component. My questions:

1. Could someone please check if it looks fine so I can start adding the rest of my components?
2. After we created the components in this manner, are we supposed to create workflows ourselves or will you do it?

Thanks,

Rodrigo
[en-ixa-pipes.zip](https://github.com/openminted/Open-Call-Discussions/files/1901992/en-ixa-pipes.zip)

**Comment by galanisd** [comment]
I guess that I can close this issue since we have already discussed everything  in 
https://github.com/openminted/Open-Call-Discussions/issues/28
