### ISSUE TITLE
WS registered but cannot find it in Galaxy

### ISSUE THREAD

**Issue by martavillegas** [openminted/Open-Call-Discussions#25]
Hi,

We registered a WS but cannot see it in Galaxy workflow editor. https://test.openminted.eu/landingPage/component/502ebdcc-aae6-4a76-ba24-b425c7ecae66

**Comment by galanisd** [comment]
It  appears in the Docker section.

![nlprot](https://user-images.githubusercontent.com/10739759/38676723-968f012e-3e64-11e8-8c73-739f396bd5b9.png)

**Comment by gkirtzou** [comment]
I can see it in the workflow editor on the left panel under the Docker label. Although when I use the search box in the left panel I cannot see it.
![screenshot at 2018-04-12 15-18-25](https://user-images.githubusercontent.com/8426223/38676838-fadb3fa8-3e64-11e8-8224-18d5d1a4ccb3.png)

**Comment by martavillegas** [comment]
Search function in Galaxy does not work: I search for NLProt  and get no results ...
![image](https://user-images.githubusercontent.com/6735707/38682945-9ba168de-3e6c-11e8-9df4-3560af0da945.png)

**Comment by greenwoodma** [comment]
Must have been a temporary glitch as it works now

![screenshot from 2018-04-16 11-42-19](https://user-images.githubusercontent.com/3025272/38804729-4ac958c0-416b-11e8-8ccb-2071f0f203d2.png)
