### ISSUE TITLE
Registered WS do not work properly

### ISSUE THREAD

**Issue by martavillegas** [openminted/Open-Call-Discussions#3]
I copy here the mail received from  the OntoGene/BioMeXT team:

"I have registered a component/application for our web service both in the test and the production stage (test.openminted.eu and services.openminted.eu). However, when I try to run the service from the OpenMinTeD site, the process does not terminate. Our web service – which should be called by the component – does not receive any requests. I see no way of diagnosing what is going wrong, as the web interface doesn't give any feedback."

**Comment by greenwoodma** [comment]
Closing as without any input from the original bug reporter it's impossible to follow up. However, the same problem is probably covered by other issues which are being actively looked at so this should be solved as a by product regardless.
