### ISSUE TITLE
Login issue for http://courses.fosteropenscience.eu/#user/login

### ISSUE THREAD

**Issue by dumitrescustefan** [openminted/Open-Call-Discussions#40]
Hello, 

Regarding the tutorials we have to do for deliverable T4, in the link here https://docs.google.com/document/d/1FRMWts3oshYOL6SBJgm-EqWzZ1yfL1C093e2g6P3Dd4/edit# says that we should login at http://courses.fosteropenscience.eu/ but I cannot see any "register" button. I tried registering on http://www.fosteropenscience.eu/ but using the user/pass on the "courses." domain doesn't work.  

I also installed the adapt tool on a local virtual machine, created a user, etc., and I can add a new course, but then how do I migrate the course from my local machine to the server at fosteropenscience? I read somewhere that the import/export options aren't fully supported. Plus I can't login there.

Thanks for the pointers,
Stefan

**Comment by pennyl67** [comment]
@dumitrescustefan Can you take up this issue with Nancy.Pontika@open.ac.uk? She's responsible for foster and tutorials.
