### ISSUE TITLE
Dockerized Component Submission

### ISSUE THREAD

**Issue by cujof1** [openminted/Open-Call-Discussions#5]
Guestncolic@gmail.com | April 6, 2018 2:52 pm Dear Mesdames & Messieurs 

We're submitting our tool which is a web interface that automatically generates a term dictionary from various resources such as MeSH, Chebi etc. that the user can select through a web interface. We're making this tool available as a docker image, so the user can run the web interface from within the Docker image and download his own aggregation of terms manually. 

However, I'm unsure about what's the best way to include the Docker image to OMTD: As a component, it needs to comply with the interoperability standards, which require the Docker image to be calleable with --input and --output parameters, and consume and produce XMI format. However, since we're supplying a manually operated interface, these requirements don't make sense. 

What is your recommendation on how to proceed? Should we upload the Docker image as a resource, so users can download it, run it locally? Or should we submit as a component and ignore the interoperability requirements that do not apply? 

Kind regards & thanks for your help, 
- Nico

**Comment by reckart** [comment]
Do you have an actual processing component which can make use of the generated dictionaries and use them to annotate text documents? That would be suitable for submission. 

IMHO the interactive web application for building the dictionaries does not fit into the present concept of components and applications.

**Comment by galanisd** [comment]
> IMHO the interactive web application for building the dictionaries does not fit into the present concept of components and applications.

Fully agree with @reckart.

**Comment by Aequivinius** [comment]
Thank you for your speedy reply. 

We're registering a named entity recogniser called OGER as a webservice (http://www.ontogene.org/resources/oger). OGER uses the dictionaries that are generated by the tool I wrote initially about (called BTH). While our main contribution is OGER, we thought the community might find also BTH useful. For example, an existing dictionary-based NER system might find value in the dictionaries generated by BTH. Consequently, we wanted to also register BTH so others can use it; and thus created a dockerized version that users can download and run locally.

Do you see any way how we can provide this auxiliary tool to OMTD?

**Comment by reckart** [comment]
What do you currently offer your dictionary building tools as? It is an open source software? Is it an online service that you host somewhere? Is it both?

**Comment by Aequivinius** [comment]
Currently, we offer it as a web service; which for OMTD we are distributing as a docker image. However, since the dictionary generation is not usually done frequently, we didn’t include an API for our webservice. So currently, we rely on the user to manually select desired resouces and download them.

Thanks for your help & kind regards,
 - Nico Colic

**Comment by reckart** [comment]
@Aequivinius If you already have a site up and running where people can go to build the dictionaries, then my suggestion would be to include a link to that site in the description of the OGER component that you register with OpenMinTeD. So people wanting to use the component with a custom dictionary could go to your site, build one, and then use it on OpenMinTeD.

However, we would need to see how that can actually be done: i.e. in which way a dictionary built on your website could be used on OMTD.

**Comment by Aequivinius** [comment]
There's an instance of our dictionary aggregation service online here: https://pub.cl.uzh.ch/projects/ontogene/biotermhub/

However, for OMTD we've already created a dockerized version that users can run locally, which is what we would like to submit. The solution @reckart recommends means that we cannot use the docker image, which would be a bit of a pity.

**Comment by reckart** [comment]
@Aequivinius you can still make benefit from the Docker image that you have created. Publish it on DockerHub and provider instructions on your website how people can get the image from there to run it on their local machines. Docker greatly facilitates deployment and your users should benefit from that.
