### ISSUE TITLE
Unable to edit workflow

### ISSUE THREAD

**Issue by reckart** [openminted/Open-Call-Discussions#7]
I have created and saved a workflow named "Simple variable disambiguation workflow" with multiple components inside it (omtd-importer, pdfreader, segmenter, disambiguator).

But when I press the "edit workflow" for this application under "my applications", I only get an empty workflow editor. How can I edit my workflow again?

Instance: test.openminted.eu

The failing workflow in #6 might be related to this issue.

**Comment by galanisd** [comment]
Unassigned myself. It has to do with how OMTD Registry uses Galaxy (the instance that is used for editing).

**Comment by reckart** [comment]
FYI @azielinskiACC

**Comment by galanisd** [comment]
@antleb and @courado I think are the most appropriate for answering your question.

**Comment by courado** [comment]
@reckart I tried to do the same, but I could edit the workflow.
How did you create the application, and can you provide its id?

**Comment by reckart** [comment]
@courado meanwhile I had to delete the workflow because I had to delete the components that were used in the workflow in order to reupload them.

The URL was:  https://test.openminted.eu/landingPage/application/c58d1986-690e-40b9-b408-f649443c7d33

Maybe you can still find it somewhere under that ID or see in the logs why it ended up being empty.

On the later attempts of building workflows, I could re-open them and they were not empty. So my guess: the empty workflow was caused by some kind of bug that triggers only is specific circumstances.

**Comment by courado** [comment]
@reckart also @galanisd maybe relevant: but when I was creating a new workflow using the galaxy editor, I added some random components and the workflow-service failed due to the fact that "segments" field was missing. I can't remember the actual component though, I will post it when I discover it again.

**Comment by reckart** [comment]
What is the `segments` field?

**Comment by courado** [comment]
An internal field used in the workflow editor in order to save the actual workflow.
JBlend library requires that the field exists, but I guess it is from an outdated version.

**Comment by greenwoodma** [comment]
I think we've decided this was just a random blip, so I'm closing this issue to clean up a little so we can focus in on what's left to fix.
